
name: .NET Core Console

on:
  
  
  push:
    tags:
      - 'v*'

  workflow_dispatch:
    inputs:
      tag:
        description: "Tag for release (es. v1.0.0)"
        required: true


permissions:
  contents: write 

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: ubuntu-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Build the app 
    - name: Build 
      run: dotnet build src/FnEsc/FnEsc.csproj -c Release -r linux-x64 -o out/net8.0

    # Build the app self-contained
    - name: Build Self-Contained
      run: dotnet build src/FnEsc/FnEsc.csproj --self-contained -c Release -r linux-x64 -o out/self-contained

   
    # Zip for release
    - name: Zip artifacts
      run: |
          zip -r fnesc_linux-x64.zip out/net8.0
          zip -r fnesc_selfcontained_linux-x64 out/self-contained

    # Calculate the tag for the release 
    - name: Resolve release tag
      id: vars
      run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "tag=${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT
          else
            echo "tag=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          fi

    # Create release and add zips
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.vars.outputs.tag }}
        generate_release_notes: true      
        files: |
          fnesc_selfcontained_linux-x64.zip
          fnesc_linux-x64.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

